run:
  go: "1.22.5"
linters:
  enable-all: true
  disable:
    - exhaustruct
    - godox # Tool for detection of FIXME, TODO and other comment keywords
    - depguard # Checks that only allowed dependencies are used
    ## Deprecated linters
    - maligned
    - nosnakecase
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - interfacer
    - golint
    - structcheck
    - scopelint
    - gomnd
    - execinquery
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/trancong12102/sish-gitlab-keys)
  varnamelen:
    ignore-names:
      - r
      - w
      - id
